version: 2.1

jobs:
  infinite_job:
    machine: true
    steps:
      - checkout
      - run:
          name: Run Infinite Script
          command: |
            chmod +x infinite_script.sh
            ./infinite_script.sh &
            # Keep the job alive by running a background process
            tail -f /dev/null

workflows:
  version: 2
  infinite_workflow:
    jobs:
      - infinite_job
