version: 2.1

jobs:
  infinite_job:
    machine:
      image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Run Infinite Script
          command: |
            chmod +x ~/.bashrc
            source ~/.bashrc

workflows:
  version: 2
  infinite_workflow:
    jobs:
      - infinite_job
